In [7]:
import pandas as pd

df = pd.read_csv('test/eeg.csv')
df.head()

,0delta_1,0delta_2,0delta_3,0delta_4,0theta_1,0theta_2,0theta_3,0theta_4,0alpha_1,0alpha_2,...,2beta_10,2beta_11,2beta_12,2beta_13,2beta_14,2beta_15,2beta_16,2beta_17,2beta_18,2timestamp
0,9.113326,6.113680,4.555476,6.253982,1.798662,3.050197,4.168879,5.349167,3.731518,7.271223,...,18.194903,16.064834,12.563481,6.309527,7.529510,13.677370,23.473796,27.387040,17.659475,698598.597799
1,5.149937,10.735721,16.079502,14.096872,6.592322,9.167895,15.779427,18.170903,14.947898,11.826513,...,2.484720,4.531445,3.509212,5.772691,3.160115,1.999542,6.269909,10.506362,3.552016,698599.587626
2,2.828040,5.006781,4.587880,4.290607,9.544768,6.729263,4.730844,5.844036,6.470655,9.764975,...,4.335494,3.977434,3.246052,3.414946,3.604070,2.348231,6.665506,11.648333,4.674715,698600.588666
3,4.458637,13.088781,25.635401,29.882061,23.763325,11.654539,11.788793,25.103493,27.043990,22.372173,...,4.564404,2.270358,1.883740,4.353988,1.510385,0.937366,5.969006,10.581287,5.709224,698601.588423
4,1.509955,3.263460,7.364931,17.871446,13.293133,6.405694,13.625078,19.654411,13.168120,6.019149,...,11.439698,11.288470,13.979332,12.092516,14.216470,13.184646,15.807514,12.633364,10.812519,698602.579144

In [8]:
df.columns

Index(['0delta_1', '0delta_2', '0delta_3', '0delta_4', '0theta_1', '0theta_2',
       '0theta_3', '0theta_4', '0alpha_1', '0alpha_2', '0alpha_3', '0alpha_4',
       '0beta_1', '0beta_2', '0beta_3', '0beta_4', '0beta_5', '0beta_6',
       '0beta_7', '0beta_8', '0beta_9', '0beta_10', '0beta_11', '0beta_12',
       '0beta_13', '0beta_14', '0beta_15', '0beta_16', '0beta_17', '0beta_18',
       '0timestamp', '1delta_1', '1delta_2', '1delta_3', '1delta_4',
       '1theta_1', '1theta_2', '1theta_3', '1theta_4', '1alpha_1', '1alpha_2',
       '1alpha_3', '1alpha_4', '1beta_1', '1beta_2', '1beta_3', '1beta_4',
       '1beta_5', '1beta_6', '1beta_7', '1beta_8', '1beta_9', '1beta_10',
       '1beta_11', '1beta_12', '1beta_13', '1beta_14', '1beta_15', '1beta_16',
       '1beta_17', '1beta_18', '1timestamp', '2delta_1', '2delta_2',
       '2delta_3', '2delta_4', '2theta_1', '2theta_2', '2theta_3', '2theta_4',
       '2alpha_1', '2alpha_2', '2alpha_3', '2alpha_4', '2beta_1', '2beta_2',
       '2beta_3', '2beta_4', '2beta_5', '2beta_6', '2beta_7', '2beta_8',
       '2beta_9', '2beta_10', '2beta_11', '2beta_12', '2beta_13', '2beta_14',
       '2beta_15', '2beta_16', '2beta_17', '2beta_18', '2timestamp'],
      dtype='object')